services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explain_it
      - POSTGRES_PASSWORD=password
    volumes:
      -pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: